### ISSUE TITLE
5. FixedWordlistDataModelElement wordlist descending

### ISSUE THREAD

**Issue by ernstleierzopf** [ait-aecid/aecid-parsergenerator#7]
The wordlist of FixedWordlistDataModelElement is sorted descending instead of ascending.

current behavior:
model = FixedWordlistDataModelElement('fixed0', [b'wordc', b'wordb', b'worda'] 

expected behavior:
model = FixedWordlistDataModelElement('fixed0', [b'worda', b'wordb', b'wordc']

**Comment by landauermax** [comment]
This was a design choice. For branches, it is a requirement to sort the branches in decreasing order (more specific branches have to be tested first), to avoid that the AMiner enters an incorrect branch, because there is no back-traversing during normal AMiner operation. For consistency, the list of the fixed word list was therefore also sorted in decreasing order.

**Comment by ernstleierzopf** [comment]
Fixed Tests to be descending.
